# Generated by Django 3.2.19 on 2024-09-04 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LeaveTypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(null=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveRequest', to='LeaveTypes.leavetype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveRequest', to='LeaveRequest.leavestatus')),
            ],
        ),
    ]
