# Generated by Django 4.2.16 on 2024-09-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_attendance_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='logout_time',
            field=models.DateTimeField(null=True),
        ),
    ]
