# Generated by Django 3.2.19 on 2024-09-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_alter_attendance_logout_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='status_id',
        ),
    ]
