# Generated by Django 3.2.19 on 2024-09-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user',
            new_name='user_id',
        ),
    ]
