# Generated by Django 3.2.19 on 2024-09-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_under_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='under_user',
        ),
    ]
